// Type for the park image mapping
export type ParkImageMap = {
  [key: string]: string;
};

// Map park IDs to their actual image filenames
export const parkImageMap: ParkImageMap = {
  acad: "acadia.jpg",
  arch: "arches.jpg",
  badl: "badlands.jpg",
  bibe: "bigbend.jpg",
  bisc: "biscayne.jpg",
  blca: "blackcanyon.jpg",
  brca: "brycecanyon.jpg",
  cany: "canyonlands.jpg",
  care: "capitolreef.jpg",
  cave: "carlsbadcaverns.jpg",
  chis: "channelislands.jpg",
  cong: "congaree.jpg",
  crla: "craterlake.jpg",
  cuva: "cuyahoga.jpg",
  deva: "deathvalley.jpg",
  dena: "denali.jpg",
  drto: "drytortugas.jpg",
  ever: "everglades.jpg",
  gaar: "gatesofthearctic.jpg",
  jeff: "gatewayarch.jpg",
  glac: "glacier.jpg",
  glba: "glacierbay.jpg",
  grca: "grandcanyon.jpg",
  grte: "grandteton.jpg",
  grba: "greatbasin.jpg",
  grpo: "greatsanddunes.jpg",
  grsm: "greatsmokymountains.jpg",
  gumo: "gaudalupemountains.jpg",
  hale: "haleakala.jpg",
  havo: "hawaiivolcanoes.jpg",
  hosp: "hotsprings.jpg",
  indu: "indianadunes.jpg",
  isro: "isleroyale.jpg",
  josh: "joshuatree.jpg",
  katm: "katmai.jpg",
  kefj: "kenaifjords.jpg",
  king: "kingscanyon.jpg",
  kova: "kobukvalley.jpg",
  lacl: "lakeclark.jpg",
  lavo: "lassenvolcanic.jpg",
  maca: "mammothcave.jpg",
  meve: "mesaverde.jpg",
  mora: "mountrainier.jpg",
  npsa: "nationalparkofamericansamoa.jpg",
  noca: "northcascades.jpg",
  olym: "olympic.jpg",
  pefo: "petrifiedforest.jpg",
  pinn: "pinnacles.jpg",
  redw: "redwood.jpg",
  romo: "rockymountain.jpg",
  sagu: "saguaro.jpg",
  seki: "sequoia.jpg",
  shen: "shenandoah.jpg",
  thro: "theodoreroosevelt.jpg",
  viis: "virginislands.jpg",
  voya: "voyageurs.jpg",
  whsa: "whitesands.jpg",
  wica: "windcave.jpg",
  wrst: "wrangell.jpg",
  yell: "yellowstone.jpg",
  yose: "yosemite.jpg",
  zion: "zion.jpg",
};
